sudo: required
services:
  - docker

before_install:
  - docker build -t yilong9407/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yilong9407/react-test npm test

after_success:
  - docker build -t yilong9407/multi-client ./client
  - docker build -t yilong9407/multi-nginx ./nginx
  - docker build -t yilong9407/multi-server ./server
  - docker build -t yilong9407/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push yilong9407/multi-client
  - docker push yilong9407/multi-nginx
  - docker push yilong9407/multi-server
  - docker push yilong9407/multi-worker
  # Send docker run configuration to EBS

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-304194717068
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
